
server:
  port: 9023

spring:
  application:
    name: CONFIG_SERVER

  #config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://gitlab-cts.stackroute.in/Sanjai.KumarT/forecastiq-config-server
          username: sanjai.kumart@cognizant.com
          password: Sanjai@1997
          default-label: main
#          timeout: 5
          clone-on-start: true
#          force-pull: true


management:
  security:
    enable: false
  endpoints:
    web:
      expose:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/