

server:
  port: 8082

#spring properties
spring:
  #application
  application:
    name: AUTH_SERVICE
  #h2 database
#  h2:
#    console:
#      enabled: true
#  sql:
#    init:
#      platform: h2
#  datasource:
#    url: jdbc:h2:mem:auth

  #SQL database
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth
#    username: root
#    password: 2107006
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto=update: update
  datasource:
    url: jdbc:mysql://sanjay-db.cxsqum8mcgdf.us-west-2.rds.amazonaws.com:3306/sanjay-db?createDatabaseIfNotExist=true
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    sql:
      init:
        platform: mysql
        schema-locations: classpath:data.sql

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

  #security
  security:
    user:
      name: user
      password: password



