server:
  port: 8089

#spring properties
spring:
  #application
  application:
    name: Wishlist-Service
  #SQL database
  datasource:
    url: jdbc:mysql://sanjay-db.cxsqum8mcgdf.us-west-2.rds.amazonaws.com:3306/sanjay-db?createDatabaseIfNotExist=true
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
    sql:
      init:
        platform: mysql
        schema-locations: classpath:data.sql


  #  config:
  #    import: "optional:configserver:http://localhost:9023/"




#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/




